sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-learning -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-learning npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-2-081177934285"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY